[ids]
373b:1058

[main]
# Swap Alt/Win
leftalt = leftmeta
leftmeta = leftalt

# Alt Droit devient votre touche magique
rightalt = layer(mad68_layer)

[mad68_layer]
# Touches manquantes
z = 102nd
x = S-102nd

l = G-l
5 = G-5
minus = G-minus
n = G-n
dot = G-dot
