# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 2
    gaps_out = 3
    # Use master layout instead of dwindle
    # layout = master
    col.active_border = rgb(fbff00)
    border_size = 3
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    blur {
        enabled = false
    }
    # Use round window corners
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
  animation = windows, 1, 1, default
}

windowrule = opacity 1 0.98, match:tag default-opacity
windowrule = opacity 1 0.98, match:tag terminal
windowrule = opacity 1 0.98, match:tag chromium-based-browser
windowrule = opacity 1 0.98, match:tag firefox-based-browser


